export {Button} from './Button/button';
export {Categories} from './categories';
export {Label, Section, Text} from './common';
export {Contact} from './contact';
export {ContactForm} from './contactForm';
export {Course} from './course';
export {FAQ} from './faq';
export {Footer} from './footer';
export {Header} from './header';
export {Improve} from './improve';
export {InputPhone} from './inputPhone';
export {InputSearch} from './inputSearch';
export {Intro} from './intro';
export {Page} from './page';
export {Price} from './price';
export {SearchForm} from './searchForm';
export {Select} from './select';
export {Teach} from './teach';
